[package]
name = "rust_lib_test_flutter"
version = "0.1.0"
edition = "2021"

[lib]
crate-type = ["cdylib", "staticlib"]

[dependencies]
flutter_rust_bridge = "=2.6.0"
tokio = { version = "1", features = ["full"] }